# Generated by Django 6.1.1 on 2026-10-03 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arcs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_COMPLETED', 'Task Completed'), ('GOAL_CREATED', 'Goal Created'), ('GOAL_COMPLETED', 'Goal Completed'), ('MILESTONE_COMPLETED', 'Milestone Completed'), ('HABIT_CREATED', 'Habit Created'), ('HABIT_COMPLETED', 'Habit Completed'), ('JOURNAL_CREATED', 'Journal Check-in'), ('ARC_STARTED', 'Arc Started'), ('ARC_COMPLETED', 'Arc Completed')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='arcs.arc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_e8ba16_idx'), models.Index(fields=['user', 'event_type'], name='analytics_a_user_id_77e142_idx'), models.Index(fields=['user', 'arc'], name='analytics_a_user_id_65f104_idx')],
            },
        ),
    ]
