# Generated by Django 6.1.1 on 2026-10-01 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='habitcompletion',
            options={'ordering': ['-local_date']},
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_count',
            field=models.IntegerField(default=1, help_text='Used for TARGET_COUNT or times per period'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_archived'], name='habits_habi_user_id_76b3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'local_date'], name='habits_habi_habit_i_4d2277_idx'),
        ),
    ]
