# Generated by Django 6.1.1 on 2026-10-03 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcs', '0001_initial'),
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-unlocked_at']},
        ),
        migrations.AddField(
            model_name='xpevent',
            name='arc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='arcs.arc'),
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='source_type',
            field=models.CharField(help_text="e.g., 'task', 'habit', 'milestone', 'goal', 'journal', 'arc'", max_length=50),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_d28532_idx'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', 'source_type'], name='gamificatio_user_id_5a4cd0_idx'),
        ),
    ]
