# Generated by Django 6.1.1 on 2026-10-03 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='deadline_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Receive goal and Arc deadline notices'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='gamification_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Receive rank promotions and badge unlocks'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='habit_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Receive daily habit check-in reminders'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Receive task due soon & overdue alerts'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_DUE_SOON', 'Task Due Soon'), ('TASK_OVERDUE', 'Task Overdue'), ('HABIT_REMINDER', 'Habit Reminder'), ('STREAK_MILESTONE', 'Streak Milestone'), ('GOAL_DEADLINE', 'Goal Deadline'), ('ARC_DEADLINE', 'Arc Deadline'), ('RANK_ACHIEVED', 'Rank Achieved'), ('ACHIEVEMENT_UNLOCKED', 'Achievement Unlocked')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, help_text='e.g. task, habit, goal, arc, rank, achievement', max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('dedup_key', models.CharField(help_text='Unique key ensuring strict idempotency', max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx')],
            },
        ),
    ]
